services:
  postgres:
    image: postgres:15-alpine
    container_name: shorturl-postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
    restart: unless-stopped

volumes:
  postgres_data:
